### Porting to Google Colab
The following cell enables this notebook to run from Google Colab as well as from your local machine IDE.<br>
You can change `root_directory` and/or `this_notebook_google_path` to point to the directory in your Google account, which contains this notebook, together with the `imgs` sub-directory and the rest of the files.<br>

In [1]:
import sys
import os
try:
    from google.colab import drive as google_drive # type: ignore
except:
    # no Google Colab --> fall back to local machine
    google_drive = None

if google_drive is not None:
    google_drive_directory = os.path.join('/','content','gdrive')
    google_drive.mount(google_drive_directory)
    all_projects_path = os.path.join(google_drive_directory, 'Othercomputers','My Laptop', 'projects')
else:
    all_projects_path = os.path.join('d:\\', 'projects')

project_path = os.path.join(all_projects_path,'RUNI','Thesis')
assert os.path.exists(project_path), f'Project path {project_path} not found!'
# enable import python files from this notebook's path
sys.path.append(project_path)
# enable reading images and data files from this notebook's path
os.chdir(project_path)

datasets_path = os.path.join(project_path, 'datasets')
assert os.path.exists(datasets_path), f'Datasets path {datasets_path} not found!'

output_path = os.path.join(project_path, 'output')
os.makedirs(output_path, exist_ok=True)
assert os.path.exists(output_path), f'Output path {output_path} not found!'

print(f'Current working directory: {os.getcwd()}')
print(f'Datasets path: {datasets_path}')
print(f'Output path: {output_path}')

Current working directory: d:\projects\RUNI\Thesis
Datasets path: d:\projects\RUNI\Thesis\datasets
Output path: d:\projects\RUNI\Thesis\output


In [2]:
import numpy as np

In [3]:
from python.hpc import HybridArray

Numba version: 0.60.0
numba.njit is available.
CUDA is available and will be used for GPU operations.
Printing CUDA active device attributes:
    Name:                               NVIDIA GeForce GTX 1650
    Free Memory:                        3367680 [KB]
    Total Memory:                       4193984 [KB]
    Compute capability:                 7.5
    Clock rate:                         1560.00 [MHz]
    Memory clock rate:                  4001.00 [MHz]
    Memory bus width:                   128 bits
    Memory band width (theoretical)     128.03 [GByte/Sec]
    Number of multiprocessors:          16
    Minimal grid size:                  128
    Maximum grid size:                  (2147483647, 65535, 65535)
    Maximum block dimensions:           (1024, 1024, 64)
    Maximum threads per block:          1024
    Warp size:                          32
    Maximum shared memory per block:    49152 [bytes]
    Maximum registers per block:        65536
    Total constant memory:   

# Testing random p-values in vector

In [4]:
from python.rare_weak_model.rare_weak_model import random_p_values_series
num_p_values = 100000
seed = 3
data_py = HybridArray()
data_py.realloc(shape=(num_p_values,), dtype=np.float64, use_gpu=False)
random_p_values_series(p_values_output=data_py, seed=seed, use_njit=False)
print(f'{data_py.numpy().mean()=}')


data_njit = HybridArray()
data_njit.realloc(shape=(num_p_values,), dtype=np.float64, use_gpu=False)
random_p_values_series(p_values_output=data_njit, seed=seed, use_njit=True)
print(f'{data_njit.numpy().mean()=}')

data_gpu = HybridArray()
data_gpu.realloc(shape=(num_p_values,), dtype=np.float64, use_gpu=True)
random_p_values_series(p_values_output=data_gpu, seed=seed)
print(f'{data_gpu.numpy().mean()=}')

data_py.numpy().mean()=0.5002764624347839
data_njit.numpy().mean()=0.5002764624347839


d:\venv\thesis\Lib\site-packages\numba\cuda\dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))


data_gpu.numpy().mean()=0.5002764624347839


In [5]:
from python.rare_weak_model.rare_weak_model import random_p_values_matrix
shape = (5,5)
seed = 0
data_py = HybridArray().realloc(shape=shape, dtype=np.float64, use_gpu=False)
num_steps = 1
num_steps = 10
random_p_values_matrix(p_values_output=data_py, offset_row0=seed, offset_col0=0, num_steps=num_steps, use_njit=False)
print(f'{data_py.numpy()=}')


data_njit = HybridArray().realloc(shape=shape, dtype=np.float64, use_gpu=False)
random_p_values_matrix(p_values_output=data_njit, offset_row0=seed, offset_col0=0, num_steps=num_steps, use_njit=True)
print(f'{data_njit.numpy()=}')

data_gpu = HybridArray().realloc(shape=shape, dtype=np.float64, use_gpu=True)
random_p_values_matrix(p_values_output=data_gpu, offset_row0=seed, offset_col0=0, num_steps=num_steps)
print(f'{data_gpu.numpy()=}')

data_py.numpy()=array([[0.5026821 , 0.54580257, 0.96072045, 0.10704762, 0.85635647],
       [0.81462697, 0.12963367, 0.67156386, 0.98788386, 0.32445072],
       [0.63443802, 0.24619511, 0.02131631, 0.59151714, 0.87104361],
       [0.13928325, 0.25919254, 0.84848738, 0.71313253, 0.61695041],
       [0.64173835, 0.92926785, 0.52276469, 0.12200263, 0.05807142]])
data_njit.numpy()=array([[0.5026821 , 0.54580257, 0.96072045, 0.10704762, 0.85635647],
       [0.81462697, 0.12963367, 0.67156386, 0.98788386, 0.32445072],
       [0.63443802, 0.24619511, 0.02131631, 0.59151714, 0.87104361],
       [0.13928325, 0.25919254, 0.84848738, 0.71313253, 0.61695041],
       [0.64173835, 0.92926785, 0.52276469, 0.12200263, 0.05807142]])


d:\venv\thesis\Lib\site-packages\numba\cuda\dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))


data_gpu.numpy()=array([[0.5026821 , 0.54580257, 0.96072045, 0.10704762, 0.85635647],
       [0.81462697, 0.12963367, 0.67156386, 0.98788386, 0.32445072],
       [0.63443802, 0.24619511, 0.02131631, 0.59151714, 0.87104361],
       [0.13928325, 0.25919254, 0.84848738, 0.71313253, 0.61695041],
       [0.64173835, 0.92926785, 0.52276469, 0.12200263, 0.05807142]])


In [6]:
from python.rare_weak_model.rare_weak_model import random_modified_p_values_matrix
shape = (5,5)
seed = 0
data_py = HybridArray().realloc(shape=shape, dtype=np.float64, use_gpu=False)
num_steps = 1
num_steps = 10
mu = 1
random_modified_p_values_matrix(p_values_output=data_py, mu=mu, offset_row0=seed, offset_col0=0, num_steps=num_steps, use_njit=False)
print(f'{data_py.numpy()=}')


data_njit = HybridArray().realloc(shape=shape, dtype=np.float64, use_gpu=False)
random_modified_p_values_matrix(p_values_output=data_njit, mu=mu, offset_row0=seed, offset_col0=0, num_steps=num_steps, use_njit=True)
print(f'{data_njit.numpy()=}')

data_gpu = HybridArray().realloc(shape=shape, dtype=np.float64, use_gpu=True)
random_modified_p_values_matrix(p_values_output=data_gpu, mu=mu, offset_row0=seed, offset_col0=0, num_steps=num_steps)
print(f'{data_gpu.numpy()=}')

data_py.numpy()=array([[0.16028751, 0.18809541, 0.77610614, 0.01246831, 0.52555148],
       [0.45821836, 0.01666338, 0.28918595, 0.8949747 , 0.07279465],
       [0.2557933 , 0.0458486 , 0.00123378, 0.22108006, 0.5522461 ],
       [0.01860078, 0.04989869, 0.51195353, 0.33089593, 0.24117783],
       [0.26209799, 0.68095106, 0.1728644 , 0.01519254, 0.00506776]])
data_njit.numpy()=array([[0.16028751, 0.18809541, 0.77610614, 0.01246831, 0.52555148],
       [0.45821836, 0.01666338, 0.28918595, 0.8949747 , 0.07279465],
       [0.2557933 , 0.0458486 , 0.00123378, 0.22108006, 0.5522461 ],
       [0.01860078, 0.04989869, 0.51195353, 0.33089593, 0.24117783],
       [0.26209799, 0.68095106, 0.1728644 , 0.01519254, 0.00506776]])


d:\venv\thesis\Lib\site-packages\numba\cuda\dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))


data_gpu.numpy()=array([[0.16028751, 0.18809541, 0.77610614, 0.01246831, 0.52555148],
       [0.45821836, 0.01666338, 0.28918595, 0.8949747 , 0.07279465],
       [0.2557933 , 0.0458486 , 0.00123378, 0.22108006, 0.5522461 ],
       [0.01860078, 0.04989869, 0.51195353, 0.33089593, 0.24117783],
       [0.26209799, 0.68095106, 0.1728644 , 0.01519254, 0.00506776]])


In [7]:
from python.rare_weak_model.rare_weak_model import rare_weak_model
shape = (5,5)
n1 = 2
seed = 0
data_py = HybridArray().realloc(shape=shape, dtype=np.float64, use_gpu=False)
counts_py = HybridArray()
num_steps = 1
mu = 1
rare_weak_model(sorted_p_values_output=data_py, cumulative_counts_output=counts_py, mu=mu, n1=n1, num_steps=num_steps, use_njit=False, sort_labels=False)
print(f'Original values N={shape[1]} {n1=}\n{data_py.numpy()}')


rare_weak_model(sorted_p_values_output=data_py, cumulative_counts_output=counts_py, mu=mu, n1=n1, use_njit=False)
print('\nNative Python:')
print(f'data=\n{data_py.numpy()}')
print(f'counts=\n{counts_py.numpy()}')

data_njit = HybridArray().realloc(shape=shape, dtype=np.float64, use_gpu=False)
counts_njit = HybridArray()
rare_weak_model(sorted_p_values_output=data_njit, cumulative_counts_output=counts_njit, mu=mu, n1=n1, use_njit=True)
print('\nNumba NJIT')
print(f'data=\n{data_njit.numpy()}')
print(f'counts=\n{counts_njit.numpy()}')

data_gpu = HybridArray().realloc(shape=shape, dtype=np.float64, use_gpu=True)
counts_gpu = HybridArray()
rare_weak_model(sorted_p_values_output=data_gpu, cumulative_counts_output=counts_gpu, mu=mu, n1=n1)
print('\nNumba CUDA')
print(f'data=\n{data_gpu.numpy()}')
print(f'counts=\n{counts_gpu.numpy()}')

Original values N=5 n1=2
[[0.05673545 0.16622495 0.23860856 0.39280115 0.59610853]
 [0.03518283 0.12296948 0.43450244 0.49564988 0.49807309]
 [0.21532803 0.28434879 0.36328378 0.46521514 0.85837417]
 [0.12733791 0.31513581 0.42174821 0.61900583 0.81407409]
 [0.03489916 0.19571534 0.20613945 0.2407543  0.98123859]]

Native Python:
data=
[[0.00596535 0.03525797 0.03608516 0.28501832 0.44151926]
 [0.0130165  0.21395014 0.2997102  0.62444604 0.62525435]
 [0.28240602 0.6765417  0.7014569  0.80739647 0.90617889]
 [0.14628628 0.22627942 0.33122183 0.52415429 0.56540923]
 [0.01185262 0.04504833 0.43827133 0.56865378 0.94735358]]
counts=
[[0 1 1 2 2]
 [1 1 1 2 2]
 [0 1 1 1 2]
 [0 1 1 2 2]
 [1 2 2 2 2]]

Numba NJIT
data=
[[0.00596535 0.03525797 0.03608516 0.28501832 0.44151926]
 [0.0130165  0.21395014 0.2997102  0.62444604 0.62525435]
 [0.28240602 0.6765417  0.7014569  0.80739647 0.90617889]
 [0.14628628 0.22627942 0.33122183 0.52415429 0.56540923]
 [0.01185262 0.04504833 0.43827133 0.56865378 0

d:\venv\thesis\Lib\site-packages\numba\cuda\dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))



Numba CUDA
data=
[[0.00596535 0.03525797 0.03608516 0.28501832 0.44151926]
 [0.0130165  0.21395014 0.2997102  0.62444604 0.62525435]
 [0.28240602 0.6765417  0.7014569  0.80739647 0.90617889]
 [0.14628628 0.22627942 0.33122183 0.52415429 0.56540923]
 [0.01185262 0.04504833 0.43827133 0.56865378 0.94735358]]
counts=
[[0 1 1 2 2]
 [1 1 1 2 2]
 [0 1 1 1 2]
 [0 1 1 2 2]
 [1 2 2 2 2]]


d:\venv\thesis\Lib\site-packages\numba\cuda\dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
